### ISSUE TITLE
Feature request: display the current pair on the command line prompt

### ISSUE THREAD

**Issue by professor** [kejadlen/git-together#18]
As a developer, I expect to easily see who is currently paired on my system.

Given I have already set a pair with 'git-together with ab cd'
When I type anything on the command prompt
Then I expect to see 'ab cd' on the command prompt.

Side note: I'm willing to update pivotal workstation-setup with git-together, I'd just like to see how to print this to the command prompt.

**Comment by kejadlen** [comment]
Check it out: https://github.com/seattle-beach/bash-it/blob/master/custom/add_user_initials_to_git_prompt_info.bash#L3

**Comment by professor** [comment]
Here is how we solved it in workstation setup: https://github.com/pivotal/workstation-setup/blob/master/files/add_user_initials_to_git_prompt_info.bash

Does this knowledge belong in the readme? I'm guessing not. Let's close this issue.
