### ISSUE TITLE
Feature request: git-together pair ab cd

### ISSUE THREAD

**Issue by professor** [kejadlen/git-together#19]
As a developer, I expect to easily set who is currently paired on my system.

When I type 'git-together pair ab cd'
Then I expect them to be paired

Sidenote: I'm worried about this confusing people who have been using git pair and them not realizing that something different is going on. I'm not sure how to handle this.

**Comment by kejadlen** [comment]
That would be my worry as well, since the two tools have quite different behavior. Maybe using a git alias for people that want to keep `pair` as the subcommand would be an acceptable solution?

**Comment by professor** [comment]
What about 'git together ab cd' ?

**Comment by professor** [comment]
I'm still thinking about this topic. I'd like to +1 the `git together ab cd` suggestion. 

Here is one more reason. At the end of the workstation-setup script, we print out...
```
You can use 'git pair' (enabled) 'git duet' (enabled) or 'git with' aka git-together (installed but not enabled)
To enable git together
git=git-together' >> ~/.bash_profile
```

I'd love for that to say
```
You can use 'git pair' (enabled) 'git duet' (enabled) or 'git together' (installed but not enabled)
```

In other words, the name of the tool should also be a command. If we want only `git with` to work, then the name of the tool and repo should be `git with` instead of `git together`
