### ISSUE TITLE
Command to show currently set authors/pair

### ISSUE THREAD

**Issue by scottcode** [kejadlen/git-together#25]
Maybe I'm missing it and it already exists, but I can't figure out an easy way to determine who the currently set author(s) are. 

When I do `git with sh km` and then do `git with`, it shows all potential authors instead of the current ones. And I don't see any option like `git with --list` or `git with -l`. It would be nice to have.

**Comment by kejadlen** [comment]
You're in luck! The [last release](https://github.com/kejadlen/git-together/releases/tag/v0.1.0-alpha.13) changed this behavior so that `git with` shows the current pair and `git with --list` shows the available authors.

**Comment by scottcode** [comment]
Great, thanks for incorporating that!
