### ISSUE TITLE
git-author

### ISSUE THREAD

**Issue by kejadlen** [kejadlen/git-together#34]
- [ ] Add info on [git-author](https://github.com/xinzweb/git-author) to the README.

Maybe support this functionality in git-together?

**Comment by kejadlen** [comment]
The `Signed-off-by` is just text (since the committer is stored in the commit metadata), so I think it's reasonable to just dump all the co-authors into the commit message if possible.

That being said though, in hindsight, I want this to mess with `git`'s config as little as possible, so I think I'd rather have `git-author` be separate rather than being built into `git-together`.

**Comment by JamesMcMahon** [comment]
No sure if I understand why changing from Signed off to Co-authored would change the amount of git config that would need to be interacted with.
