### ISSUE TITLE
add `--global` option

### ISSUE THREAD

**Issue by kejadlen** [kejadlen/git-together#4]

**Comment by sentientmonkey** [comment]
Have implementation, but currently blocked on https://github.com/libgit2/libgit2/issues/4214

**Comment by sentientmonkey** [comment]
Looks like there was a bugfix in libgit that fixes this issue (https://github.com/libgit2/libgit2/commit/86a8cd9f6a039889801b5bec865a4bc3deb30f47), but it needs to get release via (https://github.com/libgit2/libgit2/releases) and vended into the latest cargo image for libgit2-sys https://github.com/alexcrichton/git2-rs/tree/master/libgit2-sys

We can either merge and document the known issue or hold off until those issues are resolved (or move away from symlinking).

**Comment by khuddlefish** [comment]
@sentientmonkey Has the version of libgit that you need for this been released yet? It would be great to have a --global option :)

**Comment by kejadlen** [comment]
@sentientmonkey Can you see if this works now if you have time?

**Comment by sentientmonkey** [comment]
@professor and I going to pair on this Friday

**Comment by kejadlen** [comment]
Finally available in [0.1.0-alpha.17](https://github.com/kejadlen/git-together/releases/tag/v0.1.0-alpha.17)! Thanks for all the work, @sentientmonkey @professor @nrxus!
