### ISSUE TITLE
Latest release seg faults on Catalina

### ISSUE THREAD

**Issue by njbennett** [kejadlen/git-together#48]
Hey there,

We noticed today that running `git` with no arguments segmentation faults on our newer workstations. This has already been fixed, per issue #45, but the latest release (v0.1.0-alpha.21) available to brew install doesn't contain this fix. Could ya'll cut a new release and update the tap?

Alternatively, if you have guidance on another way we should be installing, we can follow that, but we're kinda hesitant to install the necessary Rust tooling to compile from source on our workstations.

- Nat from CF R&D

**Comment by kejadlen** [comment]
No prob. Went ahead and cut a [v0.1.0-alpha.24](https://github.com/kejadlen/git-together/releases/tag/v0.1.0-alpha.24) and made a [PR on pivotal/tap](https://github.com/pivotal-legacy/homebrew-tap/pull/164) to get it updated in Homebrew.
